services:
  app:
    image: pdf-extractext:v${VERSION}
    container_name: app
    ports:
      - 8000:8000
    networks:
      - mired
    environment:
      - TZ=${TZ}
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - MONGODB_URI=${MONGODB_URI}

networks:
  mired:
    external: true
