services:
  mongo:
    image: mongo:8.2
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mired
    environment:
      - TZ=${TZ}
      - MONGO_INITDB_USERNAME=${USERNAME}
      - MONGO_INITDB_PASSWORD=${PASSWORD}
    command: --wiredTigerCacheSizeGB 0.5
    volumes:
      - ${MONGO_DATA_PATH}:/data/db

networks:
  mired:
    external: true
