"""Business logic service for file upload and download operations.

This module provides in-memory file storage with SHA-256 checksum
validation and text file generation for downloads.
"""

import hashlib
from typing import Dict, Optional


class FileService:
    """Service for handling file operations in memory.

    This service stores files in a dictionary (memory only) with
    SHA-256 checksum as the key. No persistence to disk or database.

    Attributes:
        _storage: In-memory dictionary storing file content by checksum.

    """

    def __init__(self) -> None:
        """Initialize the file service with empty storage."""
        self._storage: Dict[str, bytes] = {}

    def generate_checksum(self, content: bytes) -> str:
        """Generate SHA-256 checksum from file content.

        Args:
            content: Binary file content.

        Returns:
            Hexadecimal SHA-256 checksum string.

        """
        return hashlib.sha256(content).hexdigest()

    def store_file(self, content: bytes, filename: str) -> str:
        """Store file content in memory with checksum as key.

        Args:
            content: Binary file content.
            filename: Original filename (stored for reference).

        Returns:
            SHA-256 checksum used as file identifier.

        """
        checksum = self.generate_checksum(content)
        self._storage[checksum] = content
        return checksum

    def get_file(self, file_id: str) -> Optional[bytes]:
        """Retrieve file content by file ID (checksum).

        Args:
            file_id: SHA-256 checksum of the file.

        Returns:
            File content as bytes, or None if not found.

        """
        return self._storage.get(file_id)

    def generate_text_content(self, file_id: str, original_size: int) -> str:
        """Generate text content for download response.

        Creates a simple text file with information about the file.

        Args:
            file_id: The file identifier (checksum).
            original_size: Size of the original file in bytes.

        Returns:
            Generated text content as string.

        """
        return (
            f"Content for file: {file_id}\n"
            f"Original size: {original_size} bytes\n"
            f"Generated by PDF-Extractext API\n"
            f"This is a test file generated from memory storage.\n"
        )

    def get_storage_info(self) -> Dict[str, int]:
        """Get information about current storage.

        Returns:
            Dictionary with storage statistics.

        """
        return {
            "total_files": len(self._storage),
            "total_bytes": sum(len(content) for content in self._storage.values()),
        }
